### ISSUE TITLE
Update python module to accomodate renaming of base functions

### ISSUE THREAD

**Issue by alexkillen** [kpu/kenlm#14]
Installing using pip no longer works since the changes made in https://github.com/kpu/kenlm/commit/500406ab44d02a113adf6ddb99c5ba3960317f4d

Pip install fails with the following errors:

python/kenlm.cpp:1430:59: error: ‘class lm::base::Model’ has no member named ‘Score’
python/kenlm.cpp:1450:57: error: ‘class lm::base::Model’ has no member named ‘Score’

python/kenlm.cpp:1637:74: error: ‘class lm::base::Model’ has no member named ‘FullScore’
python/kenlm.cpp:1693:72: error: ‘class lm::base::Model’ has no member named ‘FullScore’
