### ISSUE TITLE
Fails to build on OS X Sierra 10.12.5

### ISSUE THREAD

**Issue by dimatter** [kpu/kenlm#91]
```
... omitted ...
    In file included from ./lm/vocab.hh:7:.
    ./util/file_stream.hh:27:56: error: no member named 'move' in namespace 'std'
        FileStream(FileStream &&from) noexcept : buf_(std::move(from.buf_)), current_(from.current_), end_(from.end_), fd_(from.fd_) {
                                                      ~~~~~^
    1 error generated.
    error: command 'gcc' failed with exit status 1

... omitted ...
```

**std::move** missing.

[solution](https://cplusplusmusings.wordpress.com/2012/07/05/clang-and-standard-libraries-on-mac-os-x/)

> add -stdlib=libc++ to your command-line (Xcode settings, makefile, whatever). This tells clang to use libc++ as the standard library.
You have to tell the linker to link against libc++ instead of libstdc++ as well.

**Comment by eisneim** [comment]
same issue here, but when i add `-stdlib=libc++` in setup.py
```
ARGS = ['-O3', '-DNDEBUG', '-DKENLM_MAX_ORDER=6', '-std=c++11', '-stdlib=libc++']
```
i got this error:
```
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
error: command '/usr/bin/clang' failed with exit status 1
```

**Comment by kpu** [comment]
It only uses `std::move` inside
`#if __cplusplus >= 201103L`
which you will note corresponds to C++11.  What __cplusplus does your compiler define?  I guess I could disable that for OS X in general.

**Comment by kpu** [comment]
If you can come up with a more strict preprocessor test, I'll add it.  The `std::move` isn't needed for basic kenlm, but it is nice if C++11 people use the library and want move support.

**Comment by rmsmith88** [comment]
This caused me some problems here is my log and what got it working for me.

```
(py35-ds) Robs-MBP:~ rob$ virtualenv --python=python3.5 ./py35-test
Running virtualenv with interpreter /Users/rob/py35-ds/bin/python3.5
Using real prefix '/Library/Frameworks/Python.framework/Versions/3.5'
New python executable in /Users/rob/py35-test/bin/python3.5
Also creating executable in /Users/rob/py35-test/bin/python
Installing setuptools, pip, wheel...done.
(py35-ds) Robs-MBP:~ rob$ source ~/py35-test/bin/activate
(py35-test) Robs-MBP:~ rob$ pip install https://github.com/kpu/kenlm/archive/master.zip
Collecting https://github.com/kpu/kenlm/archive/master.zip
  Downloading https://github.com/kpu/kenlm/archive/master.zip (517kB)
    100% |████████████████████████████████| 522kB 121kB/s
Installing collected packages: kenlm
  Running setup.py install for kenlm ... error
    Complete output from command /Users/rob/py35-test/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/rz/jrwx6h9s6n5gb7yw71mf6vzh0000gn/T/pip-x06u7ddn-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/rz/jrwx6h9s6n5gb7yw71mf6vzh0000gn/T/pip-677zby4y-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/rob/py35-test/bin/../include/site/python3.5/kenlm:
    running install
    running build
    running build_ext
    building 'kenlm' extension
    creating build
    creating build/temp.macosx-10.6-intel-3.5
    creating build/temp.macosx-10.6-intel-3.5/util
    creating build/temp.macosx-10.6-intel-3.5/lm
    creating build/temp.macosx-10.6-intel-3.5/util/double-conversion
    creating build/temp.macosx-10.6-intel-3.5/python
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c util/bit_packing.cc -o build/temp.macosx-10.6-intel-3.5/util/bit_packing.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c util/ersatz_progress.cc -o build/temp.macosx-10.6-intel-3.5/util/ersatz_progress.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c util/exception.cc -o build/temp.macosx-10.6-intel-3.5/util/exception.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c util/file.cc -o build/temp.macosx-10.6-intel-3.5/util/file.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c util/file_piece.cc -o build/temp.macosx-10.6-intel-3.5/util/file_piece.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
    In file included from util/file_piece.cc:3:
    In file included from ./util/double-conversion/double-conversion.h:31:
    ./util/double-conversion/utils.h:302:16: warning: unused typedef 'VerifySizesAreEqual' [-Wunused-local-typedef]
      typedef char VerifySizesAreEqual[sizeof(Dest) == sizeof(Source) ? 1 : -1]
                   ^
    1 warning generated.
    In file included from util/file_piece.cc:3:
    In file included from ./util/double-conversion/double-conversion.h:31:
    ./util/double-conversion/utils.h:302:16: warning: unused typedef 'VerifySizesAreEqual' [-Wunused-local-typedef]
      typedef char VerifySizesAreEqual[sizeof(Dest) == sizeof(Source) ? 1 : -1]
                   ^
    1 warning generated.
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c util/float_to_string.cc -o build/temp.macosx-10.6-intel-3.5/util/float_to_string.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
    In file included from util/float_to_string.cc:3:
    In file included from ./util/double-conversion/double-conversion.h:31:
    ./util/double-conversion/utils.h:302:16: warning: unused typedef 'VerifySizesAreEqual' [-Wunused-local-typedef]
      typedef char VerifySizesAreEqual[sizeof(Dest) == sizeof(Source) ? 1 : -1]
                   ^
    1 warning generated.
    In file included from util/float_to_string.cc:3:
    In file included from ./util/double-conversion/double-conversion.h:31:
    ./util/double-conversion/utils.h:302:16: warning: unused typedef 'VerifySizesAreEqual' [-Wunused-local-typedef]
      typedef char VerifySizesAreEqual[sizeof(Dest) == sizeof(Source) ? 1 : -1]
                   ^
    1 warning generated.
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c util/integer_to_string.cc -o build/temp.macosx-10.6-intel-3.5/util/integer_to_string.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c util/mmap.cc -o build/temp.macosx-10.6-intel-3.5/util/mmap.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c util/murmur_hash.cc -o build/temp.macosx-10.6-intel-3.5/util/murmur_hash.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c util/parallel_read.cc -o build/temp.macosx-10.6-intel-3.5/util/parallel_read.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c util/pool.cc -o build/temp.macosx-10.6-intel-3.5/util/pool.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c util/read_compressed.cc -o build/temp.macosx-10.6-intel-3.5/util/read_compressed.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c util/scoped.cc -o build/temp.macosx-10.6-intel-3.5/util/scoped.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c util/spaces.cc -o build/temp.macosx-10.6-intel-3.5/util/spaces.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c util/string_piece.cc -o build/temp.macosx-10.6-intel-3.5/util/string_piece.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c util/usage.cc -o build/temp.macosx-10.6-intel-3.5/util/usage.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c lm/bhiksha.cc -o build/temp.macosx-10.6-intel-3.5/lm/bhiksha.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c lm/binary_format.cc -o build/temp.macosx-10.6-intel-3.5/lm/binary_format.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c lm/config.cc -o build/temp.macosx-10.6-intel-3.5/lm/config.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c lm/lm_exception.cc -o build/temp.macosx-10.6-intel-3.5/lm/lm_exception.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c lm/model.cc -o build/temp.macosx-10.6-intel-3.5/lm/model.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
    In file included from lm/model.cc:1:
    In file included from ./lm/model.hh:9:
    In file included from ./lm/search_hashed.hh:11:
    ./util/probing_hash_table.hh:68:20: warning: shift count >= width of type [-Wshift-count-overflow]
          from |= from >> 32;
                       ^  ~~
    In file included from lm/model.cc:1:
    In file included from ./lm/model.hh:13:
    In file included from ./lm/vocab.hh:7:
    ./util/file_stream.hh:27:56: error: no member named 'move' in namespace 'std'
        FileStream(FileStream &&from) noexcept : buf_(std::move(from.buf_)), current_(from.current_), end_(from.end_), fd_(from.fd_) {
                                                      ~~~~~^
    1 warning and 1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1

    ----------------------------------------
Command "/Users/rob/py35-test/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/rz/jrwx6h9s6n5gb7yw71mf6vzh0000gn/T/pip-x06u7ddn-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/rz/jrwx6h9s6n5gb7yw71mf6vzh0000gn/T/pip-677zby4y-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/rob/py35-test/bin/../include/site/python3.5/kenlm" failed with error code 1 in /private/var/folders/rz/jrwx6h9s6n5gb7yw71mf6vzh0000gn/T/pip-x06u7ddn-build/
```

I downloaded https://github.com/kpu/kenlm/archive/master.zip, extracted and opened up kenlm-master/util/file_stream.hh

As kpu said, i added a processor test for OS by changing line 26 to:
`#if __cplusplus >= 201103L && ! __APPLE__`

Can then install with pip locally using:
`pip install -e kenlm-master`
