### ISSUE TITLE
Fails to compile with Boost 1.41

### ISSUE THREAD

**Issue by bartvm** [kpu/kenlm#63]
Looks like the `required` flag from Boost.Program_options is used, which was only [added in 1.41](https://svn.boost.org/trac/boost/ticket/2982). I guess the version requirement in `CMakeLists.txt` should be upped.
```
[ 85%] Building CXX object lm/CMakeFiles/partial_test.dir/partial_test.cc.o
/home/cortex-m40/kenlm/lm/kenlm_benchmark_main.cc: In function ‘int main(int, char**)’:
/home/cortex-m40/kenlm/lm/kenlm_benchmark_main.cc:200:51: error: ‘class boost::program_options::typed_value<std::basic_string<char>, char>’ has no member named ‘required’
       ("model,m", po::value<std::string>(&model)->required(), "Model to query or convert vocab ids")
                                                   ^
make[2]: *** [lm/CMakeFiles/kenlm_benchmark.dir/kenlm_benchmark_main.cc.o] Error 1
make[1]: *** [lm/CMakeFiles/kenlm_benchmark.dir/all] Error 2
```

**Comment by kpu** [comment]
Thanks for the report.  It would be pretty easy to hand-code required() in these cases if you need it.  But I'm inclined to agree that functionality introduced 7 years ago is ok to presume.

**Comment by bartvm** [comment]
My bad: it fails on 1.41 and requires **1.42**.

**Comment by jesmitty** [comment]
I noticed this thread was closed but I ran into a similar problem with boost 1.64.0 I am trying to install 2 different programs that use boost. Joshua and KenLM. I get a similar error as what was reported e.g the below:

CMakeFiles/partial_test.dir/partial_test.cc.o: In function `boost::unit_test::lazy_ostream_impl<boost::unit_test::lazy_ostream, boost::test_tools::tt_detail::print_helper_t<bool>, boost::test_tools::tt_detail::print_helper_t<bool> const&>::operator()(std::ostream&) const':
partial_test.cc:(.text._ZNK5boost9unit_test17lazy_ostream_implINS0_12lazy_ostreamENS_10test_tools9tt_detail14print_helper_tIbEERKS6_EclERSo[_ZNK5boost9unit_test17lazy_ostream_implINS0_12lazy_ostreamENS_10test_tools9tt_detail14print_helper_tIbEERKS6_EclERSo]+0x27): undefined reference to `boost::test_tools::tt_detail::print_log_value<bool>::operator()(std::ostream&, bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/partial_test] Error 1
make[1]: *** [lm/CMakeFiles/partial_test.dir/all] Error 2

**Comment by hieuhoang** [comment]
the boost unit tests are problematic. They usually work only if the boost .so files exist. If you compile boost yourself, then you have to compile it like
   ./b2 -j4 --prefix=$PWD --libdir=$PWD/lib64 --layout=system  install 
rather than
  ./b2 -j4 --prefix=$PWD --libdir=$PWD/lib64 --layout=system link=static install

**Comment by jesmitty** [comment]
I appreciate your prompt feedback. I did the above and followed it up with a "./b2 install --with=all" but still get the same error message.

**Comment by hieuhoang** [comment]
recompile kenlm from the beginning.

**Comment by jesmitty** [comment]
I appreciate you getting back so fast.  When I go to the ...joshua/src/kenlm and follow the compiling instructions:

## Compiling
Use cmake, see [BUILDING](BUILDING) for more detail.
```bash
mkdir -p build
cd build
cmake ..
make -j 4
```
I get the same errors. The following is the last few, pertinent steps, of what I see. I am sure I am missing something but don't know what.

Scanning dependencies of target partial_test
[ 84%] Building CXX object lm/CMakeFiles/model_test.dir/model_test.cc.o
[ 85%] Building CXX object lm/CMakeFiles/partial_test.dir/partial_test.cc.o
Linking CXX executable ../tests/partial_test
CMakeFiles/partial_test.dir/partial_test.cc.o: In function `boost::unit_test::lazy_ostream_impl<boost::unit_test::lazy_ostream, boost::test_tools::tt_detail::print_helper_t<bool>, boost::test_tools::tt_detail::print_helper_t<bool> const&>::operator()(std::ostream&) const':
partial_test.cc:(.text._ZNK5boost9unit_test17lazy_ostream_implINS0_12lazy_ostreamENS_10test_tools9tt_detail14print_helper_tIbEERKS6_EclERSo[_ZNK5boost9unit_test17lazy_ostream_implINS0_12lazy_ostreamENS_10test_tools9tt_detail14print_helper_tIbEERKS6_EclERSo]+0x27): undefined reference to `boost::test_tools::tt_detail::print_log_value<bool>::operator()(std::ostream&, bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/partial_test] Error 1
make[1]: *** [lm/CMakeFiles/partial_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX executable ../tests/left_test
[ 85%] Built target left_test
Linking CXX executable ../bin/kenlm_benchmark
[ 85%] Built target kenlm_benchmark
Linking CXX executable ../tests/model_test
CMakeFiles/model_test.dir/model_test.cc.o: In function `boost::unit_test::lazy_ostream_impl<boost::unit_test::lazy_ostream, boost::test_tools::tt_detail::print_helper_t<bool>, boost::test_tools::tt_detail::print_helper_t<bool> const&>::operator()(std::ostream&) const':
model_test.cc:(.text._ZNK5boost9unit_test17lazy_ostream_implINS0_12lazy_ostreamENS_10test_tools9tt_detail14print_helper_tIbEERKS6_EclERSo[_ZNK5boost9unit_test17lazy_ostream_implINS0_12lazy_ostreamENS_10test_tools9tt_detail14print_helper_tIbEERKS6_EclERSo]+0x27): undefined reference to `boost::test_tools::tt_detail::print_log_value<bool>::operator()(std::ostream&, bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/model_test] Error 1
make[1]: *** [lm/CMakeFiles/model_test.dir/all] Error 2
make: *** [all] Error 2

**Comment by kpu** [comment]
Can you run make VERBOSE=1 and post the output?  Also, what libboost_test* do you have in /usr/lib64 or any other lib directory?  If I had to guess this is classic dynamic/static link mismatch.
