### ISSUE TITLE
Cannot compile lmplz_main.cc

### ISSUE THREAD

**Issue by hyuuki** [kpu/kenlm#19]
I'm using Ubuntu 12.04.
Previously tried to compile using Boost 1.46 but failed at all due to -lboost_exception was not exist in /usr/lib.
Then, tried to compile using Boost 1.55 (/usr/local) but lmplz_main always failed while others compiled successfully. Both source code from github and from http://kheafield.com/code/kenlm.tar.gz complains the same error.

```
gcc.compile.c++ /home/***/LM/kenlm/lm/builder/bin/gcc-4.6/release/link-static/threading-multi/lmplz_main.o
/home/***/LM/kenlm/lm/builder/lmplz_main.cc: In function ‘int main(int, char**)’:
/home/***/LM/kenlm/lm/builder/lmplz_main.cc:55:72: error: no matching function for call to ‘value(uint64_t*)’
/home/***/LM/kenlm/lm/builder/lmplz_main.cc:55:72: note: candidates are:
/usr/local/include/boost/program_options/detail/value_semantic.hpp:175:5: note: template<class T> boost::program_options::typed_value<T>* boost::program_options::value()
/usr/local/include/boost/program_options/detail/value_semantic.hpp:183:5: note: template<class T> boost::program_options::typed_value<T>* boost::program_options::value(T*)

"g++"  -ftemplate-depth-128 -O3 -finline-functions -Wno-inline -Wall -pthread  -DKENLM_MAX_ORDER=6 -DNDEBUG  -I"." -I"util/double-conversion" -c -o "/home/***/LM/kenlm/lm/builder/bin/gcc-4.6/release/link-static/threading-multi/lmplz_main.o" "/home/***/LM/kenlm/lm/builder/lmplz_main.cc"

...failed gcc.compile.c++ /home/***/LM/kenlm/lm/builder/bin/gcc-4.6/release/link-static/threading-multi/lmplz_main.o...

```

So, what's wrong with my compilation since I'm new to this?
